Repository MicrosoftDocs/cpp-docs.ko-kr, pull requests merged in 2018-12, with the labels that each got.

#85 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Accepted, Linguistic Suggestion

#90 Update floating-point-coprocessor-and-calling-conventions.md
  docs/cpp/floating-point-coprocessor-and-calling-conventions.md
Labels: Accepted, Linguistic Suggestion

#87 Update microsoft-specific-modifiers.md
  docs/cpp/microsoft-specific-modifiers.md
Labels: Accepted, Linguistic Suggestion

#80 Create template.md
  styleguide/template.md
Labels: In Progress, Linguistic Suggestion, Source Issue

#81 Update resource-files-visual-studio.md
  docs/windows/resource-files-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#82 Update index.md
  docs/linux/index.md
Labels: Accepted, Linguistic Suggestion

#83 Update parallel-programming-in-visual-cpp.md
  docs/parallel/parallel-programming-in-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#84 Update how-to-create-a-resource-script-file.md
  docs/windows/how-to-create-a-resource-script-file.md
Labels: Accepted, Linguistic Suggestion

#89 Update based-grammar.md
  docs/cpp/based-grammar.md
Labels: Accepted, Linguistic Suggestion

#91 Update calling-example-function-prototype-and-call.md
  docs/cpp/calling-example-function-prototype-and-call.md
Labels: Accepted, Linguistic Suggestion

#94 Update phases-of-translation.md
  docs/preprocessor/phases-of-translation.md
Labels: Accepted, Linguistic Suggestion

#95 Update results-of-calling-example.md
  docs/cpp/results-of-calling-example.md
Labels: Accepted, Linguistic Suggestion

#96 Update calling-conventions.md
  docs/cpp/calling-conventions.md
Labels: Accepted, Linguistic Suggestion

#97 Update func.md
  docs/cpp/func.md
Labels: Accepted, Linguistic Suggestion

#98 Update extension-restrict.md
  docs/cpp/extension-restrict.md
Labels: Accepted, Linguistic Suggestion

#99 Update noreturn.md
  docs/cpp/noreturn.md
Labels: Accepted, Linguistic Suggestion

#111 Update how-to-use-combinable-to-combine-sets.md
  docs/parallel/concrt/how-to-use-combinable-to-combine-sets.md
Labels: Accepted, Linguistic Suggestion

#125 Update comment-c-cpp.md
  docs/preprocessor/comment-c-cpp.md
Labels: Accepted, Linguistic Suggestion

#126 Update deprecated-c-cpp.md
  docs/preprocessor/deprecated-c-cpp.md
Labels: Accepted, Linguistic Suggestion

#130 Update elements-of-c.md
  docs/c-language/elements-of-c.md
Labels: Accepted, Linguistic Suggestion

#132 Update declarations-and-types.md
  docs/c-language/declarations-and-types.md
Labels: Accepted, Linguistic Suggestion

#133 Update expressions-and-assignments.md
  docs/c-language/expressions-and-assignments.md
Labels: Accepted, Linguistic Suggestion

#134 Update statements-c.md
  docs/c-language/statements-c.md
Labels: Accepted, Linguistic Suggestion

#135 Update functions-c.md
  docs/c-language/functions-c.md
Labels: Accepted, Linguistic Suggestion

#136 Update c-language-syntax-summary.md
  docs/c-language/c-language-syntax-summary.md
Labels: Accepted, Linguistic Suggestion

#137 Update implementation-defined-behavior.md
  docs/c-language/implementation-defined-behavior.md
Labels: Accepted, Linguistic Suggestion

#138 Update translation-diagnostics.md
  docs/c-language/translation-diagnostics.md
Labels: Accepted, Linguistic Suggestion

#139 Update environment.md
  docs/c-language/environment.md
Labels: Accepted, Linguistic Suggestion

#140 Update characters.md
  docs/c-language/characters.md
Labels: Accepted, Linguistic Suggestion

#142 Update integers.md
  docs/c-language/integers.md
Labels: Accepted, Linguistic Suggestion

#143 Update floating-point-math.md
  docs/c-language/floating-point-math.md
Labels: Accepted, Linguistic Suggestion

#144 Update arrays-and-pointers.md
  docs/c-language/arrays-and-pointers.md
Labels: Accepted, Linguistic Suggestion

#145 Update registers-availability-of-registers.md
  docs/c-language/registers-availability-of-registers.md
Labels: Accepted, Linguistic Suggestion

#148 Update declarators-maximum-number.md
  docs/c-language/declarators-maximum-number.md
Labels: Accepted, Linguistic Suggestion

#149 Update statements-limits-on-switch-statements.md
  docs/c-language/statements-limits-on-switch-statements.md
Labels: Accepted, Linguistic Suggestion

#150 Update preprocessing-directives.md
  docs/c-language/preprocessing-directives.md
Labels: Accepted, Linguistic Suggestion

#151 Update library-functions.md
  docs/c-language/library-functions.md
Labels: Accepted, Linguistic Suggestion

#101 Update preprocessor-directives.md
  docs/preprocessor/preprocessor-directives.md
Labels: Accepted, Linguistic Suggestion

#103 Update c-cpp-language-and-standard-libraries.md
  docs/cpp/c-cpp-language-and-standard-libraries.md
Labels: Accepted, Linguistic Suggestion

#104 Update noinline.md
  docs/cpp/noinline.md
Labels: In Progress, Linguistic Suggestion

#106 Update property-cpp.md
  docs/cpp/property-cpp.md
Labels: Accepted, Linguistic Suggestion

#108 Update multithreading-support-for-older-code-visual-cpp.md
  docs/parallel/multithreading-support-for-older-code-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#110 Update include-files-for-multithreading.md
  docs/parallel/include-files-for-multithreading.md
Labels: Accepted, Linguistic Suggestion

#112 Update how-to-use-cancellation-to-break-from-a-parallel-loop.md
  docs/parallel/concrt/how-to-use-cancellation-to-break-from-a-parallel-loop.md
Labels: Accepted, Linguistic Suggestion

#118 Update grammar-summary-c-cpp.md
  docs/preprocessor/grammar-summary-c-cpp.md
Labels: Accepted, Linguistic Suggestion

#159 Update variadic-macros.md
  docs/preprocessor/variadic-macros.md
Labels: Accepted, Linguistic Suggestion

#120 Update how-to-use-alloc-and-free-to-improve-memory-performance.md
  docs/parallel/concrt/how-to-use-alloc-and-free-to-improve-memory-performance.md
Labels: Accepted

#105 Update novtable.md
  docs/cpp/novtable.md
Labels: In Progress, Linguistic Suggestion

#109 Update library-support-for-multithreading.md
  docs/parallel/library-support-for-multithreading.md
Labels: Accepted, Linguistic Suggestion

#114 Update event-handling.md
  docs/cpp/event-handling.md
Labels: Accepted, Linguistic Suggestion

#155 Update multithread-programs.md
  docs/parallel/multithread-programs.md
Labels: Accepted, Linguistic Suggestion

#162 Fix contexts
  docs/build/vscpp-step-0-installation.md
Labels: In Progress, Linguistic Suggestion

#166 Update restrictions-on-exception-handlers.md
  docs/cpp/restrictions-on-exception-handlers.md
Labels: In Progress, Linguistic Suggestion

#121 Update definitions-for-the-grammar-summary.md
  docs/preprocessor/definitions-for-the-grammar-summary.md
Labels: Accepted, Linguistic Suggestion

#246 Update unicode-programming-summary.md
  docs/text/unicode-programming-summary.md
Labels: Accepted, Linguistic Suggestion

#117 Update objects-own-resources-raii.md
  docs/cpp/objects-own-resources-raii.md
Labels: Accepted, Linguistic Suggestion

#119 Update how-to-send-a-message-at-a-regular-interval.md
  docs/parallel/concrt/how-to-send-a-message-at-a-regular-interval.md
Labels: Accepted, Linguistic Suggestion

#262 Update expression-statement.md
  docs/cpp/expression-statement.md
Labels: Accepted, In Progress, Linguistic Suggestion

#261 Update mutable-data-members-cpp.md
  docs/cpp/mutable-data-members-cpp.md
Labels: Accepted, Linguistic Suggestion

#260 Update return-statement-in-program-termination-cpp.md
  docs/cpp/return-statement-in-program-termination-cpp.md
Labels: Accepted, Linguistic Suggestion

#259 Update abort-function.md
  docs/cpp/abort-function.md
Labels: Accepted, Linguistic Suggestion

#258 Update true-cpp.md
  docs/cpp/true-cpp.md
Labels: Accepted, Linguistic Suggestion

#124 Update pragma-directives-and-the-pragma-keyword.md
  docs/preprocessor/pragma-directives-and-the-pragma-keyword.md
Labels: Accepted, Linguistic Suggestion

#152 Update multithreading-with-c-and-win32.md
  docs/parallel/multithreading-with-c-and-win32.md
Labels: Accepted, Linguistic Suggestion

#308 Update TOC.md
  docs/text/TOC.md
Labels: Accepted, Linguistic Suggestion

#285 Update using-function-name-without-parens-produces-no-code.md
  docs/build/reference/using-function-name-without-parens-produces-no-code.md
Labels: Accepted, Linguistic Suggestion

#284 Update setting-linker-options.md
  docs/build/reference/setting-linker-options.md
Labels: Accepted, Linguistic Suggestion

#283 Update importing-and-exporting-inline-functions.md
  docs/build/importing-and-exporting-inline-functions.md
Labels: Accepted, Linguistic Suggestion

#282 Update exporting-functions-from-a-dll-by-ordinal-rather-than-by-name.md
  docs/build/exporting-functions-from-a-dll-by-ordinal-rather-than-by-name.md
Labels: Accepted, Linguistic Suggestion

#281 Update exporting-cpp-functions-for-use-in-c-language-executables.md
  docs/build/exporting-cpp-functions-for-use-in-c-language-executables.md
Labels: Accepted, Linguistic Suggestion

#154 Update auto-inline.md
  docs/preprocessor/auto-inline.md
Labels: Accepted, Linguistic Suggestion

#279 Update incrementing-and-decrementing-pointers.md
  docs/text/incrementing-and-decrementing-pointers.md
Labels: Accepted, Linguistic Suggestion

#278 Update bitwise-inclusive-or-operator-pipe.md
  docs/cpp/bitwise-inclusive-or-operator-pipe.md
Labels: Accepted, Linguistic Suggestion

#277 Update bitwise-exclusive-or-operator-hat.md
  docs/cpp/bitwise-exclusive-or-operator-hat.md
Labels: Accepted, Linguistic Suggestion

#276 Update cast-operator-parens.md
  docs/cpp/cast-operator-parens.md
Labels: Accepted, Linguistic Suggestion

#274 Update casting-operators.md
  docs/cpp/casting-operators.md
Labels: Accepted, Linguistic Suggestion

#273 Update expressions-cpp.md
  docs/cpp/expressions-cpp.md
Labels: Accepted, Linguistic Suggestion

#271 Update integer-limits.md
  docs/cpp/integer-limits.md
Labels: Accepted, Linguistic Suggestion

#268 Update m128d.md
  docs/cpp/m128d.md
Labels: Accepted, Linguistic Suggestion

#267 Update m128.md
  docs/cpp/m128.md
Labels: Accepted, Linguistic Suggestion

#272 Update floating-limits.md
  docs/cpp/floating-limits.md
Labels: Accepted, Linguistic Suggestion

#264 Update mbcs-support-in-visual-cpp.md
  docs/text/mbcs-support-in-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#270 Update m128i.md
  docs/cpp/m128i.md
Labels: Accepted, Linguistic Suggestion

#269 Update general-mbcs-programming-advice.md
  docs/text/general-mbcs-programming-advice.md
Labels: Accepted, Linguistic Suggestion

#266 Update raise.md
  docs/cpp/raise.md
Labels: Accepted, Linguistic Suggestion

#255 Update optimization-pragmas-and-keywords.md
  docs/build/reference/optimization-pragmas-and-keywords.md
Labels: Accepted, Linguistic Suggestion

#256 Update dumpbin-command-line.md
  docs/build/reference/dumpbin-command-line.md
Labels: Accepted, Linguistic Suggestion

#251 Update x64-software-conventions.md
  docs/build/x64-software-conventions.md
Labels: Accepted, Linguistic Suggestion

#250 Update configuring-programs-for-64-bit-visual-cpp.md
  docs/build/configuring-programs-for-64-bit-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#244 Update support-for-using-wmain.md
  docs/text/support-for-using-wmain.md
Labels: Accepted, Linguistic Suggestion

#247 Update support-for-multibyte-character-sets-mbcss.md
  docs/text/support-for-multibyte-character-sets-mbcss.md
Labels: Accepted, Linguistic Suggestion

#160 Update library-support-for-multithreading.md
  docs/parallel/library-support-for-multithreading.md
Labels: Accepted, Linguistic Suggestion

#293 Update selection-statements-cpp.md
  docs/cpp/selection-statements-cpp.md
Labels: Accepted, Linguistic Suggestion

#292 Update numerical-limits-cpp.md
  docs/cpp/numerical-limits-cpp.md
Labels: Accepted, Linguistic Suggestion

#179 Update unicode-and-mbcs.md
  docs/text/unicode-and-mbcs.md
Labels: Accepted, Linguistic Suggestion

#178 Update text-and-strings-in-visual-cpp.md
  docs/text/text-and-strings-in-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#167 Update writing-a-termination-handler.md
  docs/cpp/writing-a-termination-handler.md
Labels: Accepted, Linguistic Suggestion

#168 Update ordering-of-cpp-arrays.md
  docs/cpp/ordering-of-cpp-arrays.md
Labels: In Progress, Linguistic Suggestion

#169 Update indirection-on-array-types.md
  docs/cpp/indirection-on-array-types.md
Labels: Accepted, Linguistic Suggestion

#171 Update startup-and-termination-cpp.md
  docs/cpp/startup-and-termination-cpp.md
Labels: Accepted, Linguistic Suggestion

#172 Update additional-termination-considerations.md
  docs/cpp/additional-termination-considerations.md
Labels: Accepted, Linguistic Suggestion

#173 Update using-atexit.md
  docs/cpp/using-atexit.md
Labels: Accepted, Linguistic Suggestion

#174 Update using-abort.md
  docs/cpp/using-abort.md
Labels: Accepted, Linguistic Suggestion

#175 Update program-termination.md
  docs/cpp/program-termination.md
Labels: In Progress, Linguistic Suggestion

#177 Update false-cpp.md
  docs/cpp/false-cpp.md
Labels: Accepted, Linguistic Suggestion

#180 Update internationalization-strategies.md
  docs/text/internationalization-strategies.md
Labels: Accepted, Linguistic Suggestion

#290 Update byte-indices.md
  docs/text/byte-indices.md
Labels: Accepted, Linguistic Suggestion

#188 Update strings-atl-mfc.md
  docs/atl-mfc-shared/strings-atl-mfc.md
Labels: Accepted, Linguistic Suggestion

#196 Update how-to-create-clr-empty-projects.md
  docs/dotnet/how-to-create-clr-empty-projects.md
Labels: Accepted, Linguistic Suggestion

#289 Update avoiding-problem-areas-with-multithread-programs.md
  docs/parallel/avoiding-problem-areas-with-multithread-programs.md
Labels: Accepted, Linguistic Suggestion

#288 Update compiling-and-linking-multithread-programs.md
  docs/parallel/compiling-and-linking-multithread-programs.md
Labels: Accepted, Linguistic Suggestion

#287 Update sample-multithread-c-program.md
  docs/parallel/sample-multithread-c-program.md
Labels: Accepted, Linguistic Suggestion

#181 Update benefits-of-character-set-portability.md
  docs/text/benefits-of-character-set-portability.md
Labels: In Progress, Linguistic Suggestion

#195 Update cpp-cli-tasks.md
  docs/dotnet/cpp-cli-tasks.md
Labels: In Progress, Linguistic Suggestion

#306 Update null-statement.md
  docs/cpp/null-statement.md
Labels: Accepted, Linguistic Suggestion

#187 Update cpp-support-library.md
  docs/dotnet/cpp-support-library.md
Labels: Accepted, Linguistic Suggestion

#305 Update member-access.md
  docs/cpp/member-access.md
Labels: Accepted, Linguistic Suggestion

#183 Update hash-error-directive-c-cpp.md
  docs/preprocessor/hash-error-directive-c-cpp.md
Labels: Accepted, Linguistic Suggestion

#304 Update subscripting.md
  docs/cpp/subscripting.md
Labels: Accepted, Linguistic Suggestion

#302 Update lexical-conventions.md
  docs/cpp/lexical-conventions.md
Labels: Accepted, Linguistic Suggestion

#301 Update arrays-in-expressions.md
  docs/cpp/arrays-in-expressions.md
Labels: Accepted, Linguistic Suggestion

#300 Update support-for-ansi.md
  docs/text/support-for-ansi.md
Labels: Accepted, Linguistic Suggestion

#299 Update buffer-overflow.md
  docs/text/buffer-overflow.md
Labels: Accepted, Linguistic Suggestion

#184 Update lock.md
  docs/dotnet/lock.md
Labels: Accepted, Linguistic Suggestion

#197 Update support-for-unicode.md
  docs/text/support-for-unicode.md
Labels: Accepted, Linguistic Suggestion

#186 Update msclr-namespace.md
  docs/dotnet/msclr-namespace.md
Labels: Accepted, Linguistic Suggestion

#297 Update character-assignment.md
  docs/text/character-assignment.md
Labels: Accepted, Linguistic Suggestion

#296 Update basic-concepts-cpp.md
  docs/cpp/basic-concepts-cpp.md
Labels: Accepted, Linguistic Suggestion

#295 Update main-function-restrictions.md
  docs/cpp/main-function-restrictions.md
Labels: Accepted, Linguistic Suggestion

#198 Update mbcs-programming-tips.md
  docs/text/mbcs-programming-tips.md
Labels: Accepted, Linguistic Suggestion

#199 Update byte-indices.md
  docs/text/byte-indices.md
Labels: Accepted, Linguistic Suggestion

#201 Update support-for-ansi.md
  docs/text/support-for-ansi.md
Labels: Accepted, Linguistic Suggestion

#202 Update custom-manipulators-with-arguments.md
  docs/standard-library/custom-manipulators-with-arguments.md
Labels: Accepted, Linguistic Suggestion

#182 Update locales-and-code-pages.md
  docs/text/locales-and-code-pages.md
Labels: Accepted, Linguistic Suggestion

#324 Update run-time-type-information.md
  docs/cpp/run-time-type-information.md
Labels: Accepted, Linguistic Suggestion

#321 Update using-exit-or-return.md
  docs/cpp/using-exit-or-return.md
Labels: Accepted, Linguistic Suggestion

#319 Update m64.md
  docs/cpp/m64.md
Labels: Accepted, Linguistic Suggestion

#318 Update logical-negation-operator-exclpt.md
  docs/cpp/logical-negation-operator-exclpt.md
Labels: Accepted, Linguistic Suggestion

#317 Update unary-plus-and-negation-operators-plus-and.md
  docs/cpp/unary-plus-and-negation-operators-plus-and.md
Labels: Accepted, Linguistic Suggestion

#312 Update void-cpp.md
  docs/cpp/void-cpp.md
Labels: Accepted, Linguistic Suggestion

#311 Update cleaning-up-resources.md
  docs/cpp/cleaning-up-resources.md
Labels: Accepted, Linguistic Suggestion

#243 Update debugging-your-provider.md
  docs/data/oledb/debugging-your-provider.md
Labels: Accepted, Linguistic Suggestion

#241 Update working-with-ole-db-provider-templates.md
  docs/data/oledb/working-with-ole-db-provider-templates.md
Labels: In Progress, Linguistic Suggestion

#240 Update updating-a-column-when-another-table-contains-a-reference-to-t…
  docs/data/oledb/updating-a-column-when-another-table-contains-a-reference-to-the-row.md
Labels: Accepted, Linguistic Suggestion

#239 Update data-source-determining-the-schema-of-the-data-source-odbc.md
  docs/data/odbc/data-source-determining-the-schema-of-the-data-source-odbc.md
Labels: In Progress, Linguistic Suggestion

#242 Update further-reading-about-the-mfc-odbc-classes.md
  docs/data/odbc/further-reading-about-the-mfc-odbc-classes.md
Labels: Accepted, Linguistic Suggestion

#238 Update odbc-driver-list.md
  docs/data/odbc/odbc-driver-list.md
Labels: Accepted, Linguistic Suggestion

#236 Update use-the-odbc-cursor-library.md
  docs/data/odbc/use-the-odbc-cursor-library.md
Labels: Accepted, Linguistic Suggestion

#234 Update work-with-odbc-database-connections.md
  docs/data/odbc/work-with-odbc-database-connections.md
Labels: Accepted, Linguistic Suggestion

#233 Update use-odbc-to-work-with-other-users.md
  docs/data/odbc/use-odbc-to-work-with-other-users.md
Labels: Accepted, Linguistic Suggestion
