Repository MicrosoftDocs/cpp-docs.ko-kr, pull requests merged in 2019-08, with the labels that each got.

#783 Update iunknown.md
  docs/atl/iunknown.md
Labels: Accepted, Linguistic Suggestion

#784 Update reference-counting.md
  docs/atl/reference-counting.md
Labels: Accepted, Linguistic Suggestion

#785 Update queryinterface.md
  docs/atl/queryinterface.md
Labels: Accepted, Linguistic Suggestion

#791 Update introduction-to-atl.md
  docs/atl/introduction-to-atl.md
Labels: Linguistic Suggestion, Partially Accepted

#787 Update marshaling.md
  docs/atl/marshaling.md
Labels: Accepted, Linguistic Suggestion

#731 Edit typing error
  docs/atl-mfc-shared/reference/crect-class.md
Labels: Accepted, Source Issue

#798 Update creating-an-aggregated-object.md
  docs/atl/creating-an-aggregated-object.md
Labels: Accepted, Linguistic Suggestion

#799 Update mfc-desktop-applications.md
  docs/mfc/mfc-desktop-applications.md
Labels: Linguistic Suggestion, Partially Accepted

#795 Update implementing-ccomobjectrootex.md
  docs/atl/implementing-ccomobjectrootex.md
Labels: Accepted, Linguistic Suggestion

#803 Update using-the-mfc-source-files.md
  docs/mfc/using-the-mfc-source-files.md
Labels: Accepted, Linguistic Suggestion

#797 Update changing-the-default-class-factory-and-aggregation-model.md
  docs/atl/changing-the-default-class-factory-and-aggregation-model.md
Labels: Accepted, Linguistic Suggestion

#801 Update mfc-concepts.md
  docs/mfc/mfc-concepts.md
Labels: Accepted, Linguistic Suggestion

#802 Update general-mfc-topics.md
  docs/mfc/general-mfc-topics.md
Labels: Accepted, Linguistic Suggestion

#806 Update decrement-implementation-comment.md
  docs/mfc/decrement-implementation-comment.md
Labels: Accepted, Linguistic Suggestion

#807 Update decrement-constructors-comment.md
  docs/mfc/decrement-constructors-comment.md
Labels: Accepted, Linguistic Suggestion

#809 Update decrement-attributes-comment.md
  docs/mfc/decrement-attributes-comment.md
Labels: Accepted, Linguistic Suggestion

#811 Update decrement-overridables-comment.md
  docs/mfc/decrement-overridables-comment.md
Labels: Accepted, Linguistic Suggestion

#813 Update mfc-mbcs-dll-add-on.md
  docs/mfc/mfc-mbcs-dll-add-on.md
Labels: Accepted, Linguistic Suggestion

#810 Update decrement-operations-comment.md
  docs/mfc/decrement-operations-comment.md
Labels: Accepted, Linguistic Suggestion

#816 Update framework-mfc.md
  docs/mfc/framework-mfc.md
Labels: Accepted, Linguistic Suggestion

#817 Update sdi-and-mdi.md
  docs/mfc/sdi-and-mdi.md
Labels: Accepted, Linguistic Suggestion

#818 Update building-on-the-framework.md
  docs/mfc/building-on-the-framework.md
Labels: Accepted, Linguistic Suggestion

#819 Update cwinapp-and-the-mfc-application-wizard.md
  docs/mfc/cwinapp-and-the-mfc-application-wizard.md
Labels: Accepted, Linguistic Suggestion

#821 Update initinstance-member-function.md
  docs/mfc/initinstance-member-function.md
Labels: Accepted, Linguistic Suggestion

#822 Update run-member-function.md
  docs/mfc/run-member-function.md
Labels: Accepted, Linguistic Suggestion

#825 Update onidle-member-function.md
  docs/mfc/onidle-member-function.md
Labels: Accepted, Linguistic Suggestion

#824 Update exitinstance-member-function.md
  docs/mfc/exitinstance-member-function.md
Labels: Accepted, Linguistic Suggestion
