Repository MicrosoftDocs/cpp-docs.ko-kr, pull requests merged in 2019-05, with the labels that each got.

#668 Update await-enable-coroutine-support.md
  docs/build/reference/await-enable-coroutine-support.md
Labels: Accepted, Linguistic Suggestion

#670 Update ptr32-ptr64.md
  docs/cpp/ptr32-ptr64.md
Labels: Accepted, Linguistic Suggestion

#674 Update cgthreads-code-generation-threads.md
  docs/build/reference/cgthreads-code-generation-threads.md
Labels: Accepted, Linguistic Suggestion

#675 Update cgthreads-code-generation-threads.md
  docs/build/reference/cgthreads-code-generation-threads.md
Labels: Accepted, Linguistic Suggestion

#676 Update doc-process-documentation-comments-c-cpp.md
  docs/build/reference/doc-process-documentation-comments-c-cpp.md
Labels: Accepted, Linguistic Suggestion

#678 Update eh-exception-handling-model.md
  docs/build/reference/eh-exception-handling-model.md
Labels: Linguistic Suggestion, Partially Accepted

#686 Update visual-cpp-language-conformance.md
  docs/overview/visual-cpp-language-conformance.md
Labels: Accepted, Technical Issue

#684 Update fa-fa-listing-file.md
  docs/build/reference/fa-fa-listing-file.md
Labels: Accepted, Linguistic Suggestion

#687 Update specifying-the-pathname.md
  docs/build/reference/specifying-the-pathname.md
Labels: Accepted, Linguistic Suggestion

#688 Update fd-ide-minimal-rebuild.md
  docs/build/reference/fd-ide-minimal-rebuild.md
Labels: Accepted, Linguistic Suggestion

#689 Update fd-program-database-file-name.md
  docs/build/reference/fd-program-database-file-name.md
Labels: Accepted, Linguistic Suggestion

#690 Update fi-preprocess-output-file-name.md
  docs/build/reference/fi-preprocess-output-file-name.md
Labels: Accepted, Linguistic Suggestion

#692 Update fm-name-mapfile.md
  docs/build/reference/fm-name-mapfile.md
Labels: Accepted, Linguistic Suggestion

#691 Update fi-name-forced-include-file.md
  docs/build/reference/fi-name-forced-include-file.md
Labels: Accepted, Linguistic Suggestion

#693 Update fo-object-file-name.md
  docs/build/reference/fo-object-file-name.md
Labels: Accepted, Linguistic Suggestion

#694 Update fp-name-dot-pch-file.md
  docs/build/reference/fp-name-dot-pch-file.md
Labels: Accepted, Linguistic Suggestion

#695 Update fr-fr-create-dot-sbr-file.md
  docs/build/reference/fr-fr-create-dot-sbr-file.md
Labels: Accepted, Linguistic Suggestion

#697 Update fu-name-forced-hash-using-file.md
  docs/build/reference/fu-name-forced-hash-using-file.md
Labels: Linguistic Suggestion, Partially Accepted

#698 Update fx-merge-injected-code.md
  docs/build/reference/fx-merge-injected-code.md
Labels: Accepted, Linguistic Suggestion

#699 Update favor-optimize-for-architecture-specifics.md
  docs/build/reference/favor-optimize-for-architecture-specifics.md
Labels: Accepted, Linguistic Suggestion

#700 Update fc-full-path-of-source-code-file-in-diagnostics.md
  docs/build/reference/fc-full-path-of-source-code-file-in-diagnostics.md
Labels: Accepted, Linguistic Suggestion

#702 Update ga-optimize-for-windows-application.md
  docs/build/reference/ga-optimize-for-windows-application.md
Labels: Accepted, Linguistic Suggestion

#701 Update fs-force-synchronous-pdb-writes.md
  docs/build/reference/fs-force-synchronous-pdb-writes.md
Labels: Accepted, Linguistic Suggestion

#703 Update gd-gr-gv-gz-calling-convention.md
  docs/build/reference/gd-gr-gv-gz-calling-convention.md
Labels: Accepted, Linguistic Suggestion
