Repository MicrosoftDocs/cpp-docs.ko-kr, pull requests merged in 2019-01, with the labels that each got.

#176 Update jump-statements-cpp.md
  docs/cpp/jump-statements-cpp.md
Labels: Accepted, Linguistic Suggestion

#343 Update const-cast-operator.md
  docs/cpp/const-cast-operator.md
Labels: Accepted, Linguistic Suggestion

#345 Update overview-of-cpp-statements.md
  docs/cpp/overview-of-cpp-statements.md
Labels: Accepted, Linguistic Suggestion

#346 Update types-of-expressions.md
  docs/cpp/types-of-expressions.md
Labels: Accepted, Linguistic Suggestion

#347 Update cpp-constant-expressions.md
  docs/cpp/cpp-constant-expressions.md
Labels: Accepted, Linguistic Suggestion

#348 Update iteration-statements-cpp.md
  docs/cpp/iteration-statements-cpp.md
Labels: Accepted, Linguistic Suggestion

#350 Update using-arrays-cpp.md
  docs/cpp/using-arrays-cpp.md
Labels: Accepted, Linguistic Suggestion

#351 Update initializing-arrays.md
  docs/cpp/initializing-arrays.md
Labels: Accepted, Linguistic Suggestion

#352 Update interpretation-of-subscript-operator.md
  docs/cpp/interpretation-of-subscript-operator.md
Labels: Accepted, Linguistic Suggestion

#364 Update cpp-exception-handling.md
  docs/cpp/cpp-exception-handling.md
Labels: Accepted, Linguistic Suggestion

#362 Update cpp-language-reference.md
  docs/cpp/cpp-language-reference.md
Labels: Accepted, Linguistic Suggestion

#363 Update restrictions-on-termination-handlers.md
  docs/cpp/restrictions-on-termination-handlers.md
Labels: Accepted, Linguistic Suggestion

#365 Update unhandled-cpp-exceptions.md
  docs/cpp/unhandled-cpp-exceptions.md
Labels: Accepted, Linguistic Suggestion

#356 Update cpp-standard-library-header-files.md
  docs/standard-library/cpp-standard-library-header-files.md
Labels: Accepted, Linguistic Suggestion

#387 Update comments-cpp.md
  docs/cpp/comments-cpp.md
Labels: In Progress, Linguistic Suggestion

#367 Update customizing-cpp-command-line-processing.md
  docs/cpp/customizing-cpp-command-line-processing.md
Labels: In Progress, Linguistic Suggestion

#354 Update typename.md
  docs/cpp/typename.md
Labels: In Progress, Linguistic Suggestion

#378 Update pimpl-for-compile-time-encapsulation-modern-cpp.md
  docs/cpp/pimpl-for-compile-time-encapsulation-modern-cpp.md
Labels: In Progress, Linguistic Suggestion

#374 Update how-to-create-and-use-unique-ptr-instances.md
  docs/cpp/how-to-create-and-use-unique-ptr-instances.md
Labels: In Progress, Linguistic Suggestion

#371 Update object-lifetime-and-resource-management-modern-cpp.md
  docs/cpp/object-lifetime-and-resource-management-modern-cpp.md
Labels: In Progress, Linguistic Suggestion

#360 Update welcome-back-to-cpp-modern-cpp.md
  docs/cpp/welcome-back-to-cpp-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#368 Update cpp-type-system-modern-cpp.md
  docs/cpp/cpp-type-system-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#369 Update value-types-modern-cpp.md
  docs/cpp/value-types-modern-cpp.md
Labels: In Progress, Linguistic Suggestion

#370 Update type-conversions-and-type-safety-modern-cpp.md
  docs/cpp/type-conversions-and-type-safety-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#372 Update objects-own-resources-raii.md
  docs/cpp/objects-own-resources-raii.md
Labels: Accepted, Linguistic Suggestion

#373 Update smart-pointers-modern-cpp.md
  docs/cpp/smart-pointers-modern-cpp.md
Labels: In Progress, Linguistic Suggestion

#395 Update exit-function.md
  docs/cpp/exit-function.md
Labels: Accepted, Linguistic Suggestion

#394 Update mapi-samples.md
  docs/mfc/mapi-samples.md
Labels: Accepted, Linguistic Suggestion

#353 Update how-to-convert-between-various-string-types.md
  docs/text/how-to-convert-between-various-string-types.md
Labels: Accepted, Linguistic Suggestion

#375 Update how-to-create-and-use-shared-ptr-instances.md
  docs/cpp/how-to-create-and-use-shared-ptr-instances.md
Labels: Accepted, Linguistic Suggestion

#376 Update how-to-create-and-use-weak-ptr-instances.md
  docs/cpp/how-to-create-and-use-weak-ptr-instances.md
Labels: Accepted, Linguistic Suggestion

#377 Update how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md
  docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md
Labels: Accepted, Linguistic Suggestion

#379 Update containers-modern-cpp.md
  docs/cpp/containers-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#381 Update string-and-i-o-formatting-modern-cpp.md
  docs/cpp/string-and-i-o-formatting-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#382 Update errors-and-exception-handling-modern-cpp.md
  docs/cpp/errors-and-exception-handling-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#383 Update how-to-design-for-exception-safety.md
  docs/cpp/how-to-design-for-exception-safety.md
Labels: Accepted, Linguistic Suggestion

#384 Update how-to-interface-between-exceptional-and-non-exceptional-code.md
  docs/cpp/how-to-interface-between-exceptional-and-non-exceptional-code.md
Labels: Accepted, Linguistic Suggestion

#385 Update portability-at-abi-boundaries-modern-cpp.md
  docs/cpp/portability-at-abi-boundaries-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#393 Update virtual-cpp.md
  docs/cpp/virtual-cpp.md
Labels: Accepted, Linguistic Suggestion

#396 Update super.md
  docs/cpp/super.md
Labels: Accepted, Linguistic Suggestion

#397 Update compound-statements-blocks.md
  docs/cpp/compound-statements-blocks.md
Labels: Accepted, Linguistic Suggestion

#412 Update overview-of-cpp-statements.md
  docs/cpp/overview-of-cpp-statements.md
Labels: Accepted, Linguistic Suggestion

#409 Update fixing-release-build-problems.md
  docs/build/reference/fixing-release-build-problems.md
Labels: Accepted, Linguistic Suggestion

#406 Update module-definition-dot-def-files.md
  docs/build/reference/module-definition-dot-def-files.md
Labels: Accepted, Linguistic Suggestion

#404 Update point-of-declaration-in-cpp.md
  docs/cpp/point-of-declaration-in-cpp.md
Labels: Accepted, Linguistic Suggestion

#402 Update punctuators-cpp.md
  docs/cpp/punctuators-cpp.md
Labels: Accepted, Linguistic Suggestion

#399 Update memory-management.md
  docs/mfc/memory-management.md
Labels: Accepted, Linguistic Suggestion

#417 Update converting-data-not-supported-by-the-provider.md
  docs/data/oledb/converting-data-not-supported-by-the-provider.md
Labels: In Progress, Linguistic Suggestion

#418 Update data-sources-and-sessions.md
  docs/data/oledb/data-sources-and-sessions.md
Labels: In Progress, Linguistic Suggestion

#413 Update creating-an-ole-db-consumer-using-a-wizard.md
  docs/data/oledb/creating-an-ole-db-consumer-using-a-wizard.md
Labels: Accepted, Linguistic Suggestion

#411 Update lambda-expressions-constexpr.md
  docs/cpp/lambda-expressions-constexpr.md
Labels: In Progress, Linguistic Suggestion

#408 Update release-builds.md
  docs/build/reference/release-builds.md
Labels: In Progress, Linguistic Suggestion

#410 Update checking-for-memory-overwrites.md
  docs/build/reference/checking-for-memory-overwrites.md
Labels: In Progress, Linguistic Suggestion

#407 Update compound-statements-blocks.md
  docs/cpp/compound-statements-blocks.md
Labels: In Progress, Linguistic Suggestion

#405 Update specifiers.md
  docs/cpp/specifiers.md
Labels: Accepted, Linguistic Suggestion

#401 Update alignof-and-alignas-cpp.md
  docs/cpp/alignof-and-alignas-cpp.md
Labels: Accepted, Linguistic Suggestion

#400 Update interface.md
  docs/cpp/interface.md
Labels: Accepted, Linguistic Suggestion

#423 Update using-an-existing-ado-recordset.md
  docs/data/oledb/using-an-existing-ado-recordset.md
Labels: In Progress, Linguistic Suggestion

#358 Update algorithm.md
  docs/standard-library/algorithm.md
Labels: In Progress, Linguistic Suggestion

#431 Update class-cpp.md
  docs/cpp/class-cpp.md
Labels: In Progress, Linguistic Suggestion

#421 Update do-while-statement-cpp.md
  docs/cpp/do-while-statement-cpp.md
Labels: In Progress, Linguistic Suggestion

#427 Update for-statement-cpp.md
  docs/cpp/for-statement-cpp.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#435 Update property-maps.md
  docs/data/oledb/property-maps.md
Labels: In Progress, Linguistic Suggestion

#437 Update struct-cpp.md
  docs/cpp/struct-cpp.md
Labels: Accepted, Linguistic Suggestion

#441 Update using-wmain-instead-of-main.md
  docs/cpp/using-wmain-instead-of-main.md
Labels: Accepted, Linguistic Suggestion

#440 Update provider-wizard-generated-files.md
  docs/data/oledb/provider-wizard-generated-files.md
Labels: Accepted, Linguistic Suggestion

#439 Update creating-the-provider.md
  docs/data/oledb/creating-the-provider.md
Labels: In Progress, Linguistic Suggestion

#438 Update main-program-startup.md
  docs/cpp/main-program-startup.md
Labels: Accepted, Linguistic Suggestion

#445 Update supporting-free-threading-in-your-provider.md
  docs/data/oledb/supporting-free-threading-in-your-provider.md
Labels: Accepted, Linguistic Suggestion

#448 Update odbc-and-the-database-classes.md
  docs/data/odbc/odbc-and-the-database-classes.md
Labels: In Progress, Linguistic Suggestion

#451 Update parsing-cpp-command-line-arguments.md
  docs/cpp/parsing-cpp-command-line-arguments.md
Labels: In Progress, Linguistic Suggestion

#452 Update access-to-odbc-and-sql.md
  docs/data/odbc/access-to-odbc-and-sql.md
Labels: In Progress, Linguistic Suggestion

#453 Update data-source-programmatically-creating-a-table-in-an-odbc-data-…
  docs/data/odbc/data-source-programmatically-creating-a-table-in-an-odbc-data-source.md
Labels: In Progress, Linguistic Suggestion

#454 Update main-function-restrictions.md
  docs/cpp/main-function-restrictions.md
Labels: In Progress, Linguistic Suggestion

#455 Update enabling-and-disabling-services-for-a-provider.md
  docs/data/oledb/enabling-and-disabling-services-for-a-provider.md
Labels: In Progress, Linguistic Suggestion

#457 Update additional-startup-considerations.md
  docs/cpp/additional-startup-considerations.md
Labels: Accepted, Linguistic Suggestion

#458 Update receiving-notifications.md
  docs/data/oledb/receiving-notifications.md
Labels: Accepted, Linguistic Suggestion

#459 Update native-and-dotnet-interoperability.md
  docs/dotnet/native-and-dotnet-interoperability.md
Labels: Accepted, Linguistic Suggestion

#460 Update cpp-standard-library-overview.md
  docs/standard-library/cpp-standard-library-overview.md
Labels: Accepted, Linguistic Suggestion

#461 Update ansi-c-compliance.md
  docs/c-runtime-library/ansi-c-compliance.md
Labels: Accepted, Linguistic Suggestion

#462 Update unix.md
  docs/c-runtime-library/unix.md
Labels: Accepted, Linguistic Suggestion

#466 Update windows-platforms-crt.md
  docs/c-runtime-library/windows-platforms-crt.md
Labels: Accepted, Linguistic Suggestion

#467 Update nullptr.md
  docs/cpp/nullptr.md
Labels: Accepted, Linguistic Suggestion

#468 Update int8-int16-int32-int64.md
  docs/cpp/int8-int16-int32-int64.md
Labels: Accepted, Linguistic Suggestion

#469 Update backward-compatibility.md
  docs/c-runtime-library/backward-compatibility.md
Labels: Accepted, Linguistic Suggestion

#470 Update equality-operators-equal-equal-and-exclpt-equal.md
  docs/cpp/equality-operators-equal-equal-and-exclpt-equal.md
Labels: Accepted, Linguistic Suggestion

#471 Update statements-cpp.md
  docs/cpp/statements-cpp.md
Labels: Accepted, Linguistic Suggestion

#475 Update type-checking-crt.md
  docs/c-runtime-library/type-checking-crt.md
Labels: Accepted, Linguistic Suggestion
