Repository MicrosoftDocs/cpp-docs.ko-kr, pull requests merged in 2019-02, with the labels that each got.

#479 Update if-not-exists-statement.md
  docs/cpp/if-not-exists-statement.md
Labels: Accepted, Linguistic Suggestion

#480 Update sal-annotations.md
  docs/c-runtime-library/sal-annotations.md
Labels: Accepted, Linguistic Suggestion

#478 Update direction-flag.md
  docs/c-runtime-library/direction-flag.md
Labels: Accepted, Linguistic Suggestion

#482 Update transfers-of-control.md
  docs/cpp/transfers-of-control.md
Labels: Accepted, Linguistic Suggestion

#483 Update identifiers-cpp.md
  docs/cpp/identifiers-cpp.md
Labels: Accepted, Linguistic Suggestion

#486 Update references-to-pointers.md
  docs/cpp/references-to-pointers.md
Labels: Accepted, Linguistic Suggestion

#489 Update reference-type-function-arguments.md
  docs/cpp/reference-type-function-arguments.md
Labels: Accepted With Changes, Linguistic Suggestion

#488 Update lvalue-reference-declarator-amp.md
  docs/cpp/lvalue-reference-declarator-amp.md
Labels: Accepted, Linguistic Suggestion

#490 Update application-settings-win-32-project-wizard.md
  docs/windows/application-settings-win-32-project-wizard.md
Labels: Accepted With Changes, Linguistic Suggestion

#493 Update safeint-functions.md
  docs/windows/safeint-functions.md
Labels: Accepted, Linguistic Suggestion

#492 Update safeint-class.md
  docs/windows/safeint-class.md
Labels: Accepted, Linguistic Suggestion

#494 Update safeintexception-class.md
  docs/windows/safeintexception-class.md
Labels: Accepted With Changes, Linguistic Suggestion

#496 Update internationalization-strategies.md
  docs/text/internationalization-strategies.md
Labels: Accepted, Linguistic Suggestion

#495 Update class-member-overview.md
  docs/cpp/class-member-overview.md
Labels: Accepted, Linguistic Suggestion

#501 Update retrieving-a-blob.md
  docs/data/oledb/retrieving-a-blob.md
Labels: Accepted With Changes, Linguistic Suggestion

#502 Update creating-the-project-atl-tutorial-part-1.md
  docs/atl/creating-the-project-atl-tutorial-part-1.md
Labels: Accepted With Changes, Linguistic Suggestion

#504 Update introduction-to-com-and-atl.md
  docs/atl/introduction-to-com-and-atl.md
Labels: Accepted With Changes, Linguistic Suggestion

#497 Update string-and-i-o-formatting-modern-cpp.md
  docs/cpp/string-and-i-o-formatting-modern-cpp.md
Labels: Accepted With Changes, Linguistic Suggestion

#498 Update using-stored-procedures.md
  docs/data/oledb/using-stored-procedures.md
Labels: Accepted, Linguistic Suggestion

#499 Update using-multiple-result-sets-from-one-stored-procedure.md
  docs/data/oledb/using-multiple-result-sets-from-one-stored-procedure.md
Labels: Accepted With Changes, Linguistic Suggestion

#500 Update using-ole-db-record-views.md
  docs/data/oledb/using-ole-db-record-views.md
Labels: Accepted With Changes, Linguistic Suggestion

#506 Update adding-a-control-atl-tutorial-part-2.md
  docs/atl/adding-a-control-atl-tutorial-part-2.md
Labels: Accepted With Changes, Linguistic Suggestion

#509 Update introduction-to-com.md
  docs/atl/introduction-to-com.md
Labels: Accepted With Changes, Linguistic Suggestion

#510 Update interfaces-atl.md
  docs/atl/interfaces-atl.md
Labels: Accepted With Changes, Linguistic Suggestion

#511 Update iunknown.md
  docs/atl/iunknown.md
Labels: Accepted With Changes, Linguistic Suggestion

#512 Update introduction-to-atl.md
  docs/atl/introduction-to-atl.md
Labels: Accepted With Changes, Linguistic Suggestion

#513 Update attributes-by-group.md
  docs/windows/attributes/attributes-by-group.md
Labels: Accepted With Changes, Linguistic Suggestion

#516 Update function-templates.md
  docs/cpp/function-templates.md
Labels: Accepted, Linguistic Suggestion

#515 Update class-templates.md
  docs/cpp/class-templates.md
Labels: Accepted With Changes, Linguistic Suggestion

#517 Update explicit-instantiation.md
  docs/cpp/explicit-instantiation.md
Labels: Accepted With Changes, Linguistic Suggestion

#520 Update cpp-attributes-com-net.md
  docs/windows/attributes/cpp-attributes-com-net.md
Labels: Accepted With Changes, Linguistic Suggestion

#526 Update uniform-initialization-and-delegating-constructors.md
  docs/cpp/uniform-initialization-and-delegating-constructors.md
Labels: Accepted, Linguistic Suggestion

#518 Update com-attributes.md
  docs/windows/attributes/com-attributes.md
Labels: Linguistic Suggestion, Partially accepted

#522 Update attributes-alphabetical-reference.md
  docs/windows/attributes/attributes-alphabetical-reference.md
Labels: Linguistic Suggestion, Partially accepted

#539 Update how-to-design-for-exception-safety.md
  docs/cpp/how-to-design-for-exception-safety.md
Labels: Accepted, Linguistic Suggestion

#538 Update errors-and-exception-handling-modern-cpp.md
  docs/cpp/errors-and-exception-handling-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#537 Update string-and-i-o-formatting-modern-cpp.md
  docs/cpp/string-and-i-o-formatting-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#536 Update algorithms-modern-cpp.md
  docs/cpp/algorithms-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#535 Update containers-modern-cpp.md
  docs/cpp/containers-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#534 Update pimpl-for-compile-time-encapsulation-modern-cpp.md
  docs/cpp/pimpl-for-compile-time-encapsulation-modern-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#533 Update how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md
  docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md
Labels: Accepted, Linguistic Suggestion

#532 Update how-to-create-and-use-weak-ptr-instances.md
  docs/cpp/how-to-create-and-use-weak-ptr-instances.md
Labels: Accepted, Linguistic Suggestion

#528 Update objects-own-resources-raii.md
  docs/cpp/objects-own-resources-raii.md
Labels: Accepted, Linguistic Suggestion

#541 Update portability-at-abi-boundaries-modern-cpp.md
  docs/cpp/portability-at-abi-boundaries-modern-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#540 Update how-to-interface-between-exceptional-and-non-exceptional-code.md
  docs/cpp/how-to-interface-between-exceptional-and-non-exceptional-code.md
Labels: Accepted, Linguistic Suggestion

#531 Update how-to-create-and-use-shared-ptr-instances.md
  docs/cpp/how-to-create-and-use-shared-ptr-instances.md
Labels: Accepted, Linguistic Suggestion

#530 Update how-to-create-and-use-unique-ptr-instances.md
  docs/cpp/how-to-create-and-use-unique-ptr-instances.md
Labels: Accepted, Linguistic Suggestion

#529 Update smart-pointers-modern-cpp.md
  docs/cpp/smart-pointers-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#527 Update object-lifetime-and-resource-management-modern-cpp.md
  docs/cpp/object-lifetime-and-resource-management-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#525 Update type-conversions-and-type-safety-modern-cpp.md
  docs/cpp/type-conversions-and-type-safety-modern-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#524 Update value-types-modern-cpp.md
  docs/cpp/value-types-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#523 Update cpp-type-system-modern-cpp.md
  docs/cpp/cpp-type-system-modern-cpp.md
Labels: Accepted, Linguistic Suggestion

#542 Update algorithms-modern-cpp.md
  docs/cpp/algorithms-modern-cpp.md
Labels: Linguistic Suggestion, Partially accepted

#544 Update TOC.md
  docs/cpp/TOC.md
Labels: Linguistic Suggestion, Partially accepted

#561 Update c-cpp-building-reference.md
  docs/build/reference/c-cpp-building-reference.md
Labels: Accepted, Linguistic Suggestion

#554 Update nonstandard-behavior.md
  docs/cpp/nonstandard-behavior.md
Labels: Linguistic Suggestion, Partially Accepted

#553 Update compiler-limits.md
  docs/cpp/compiler-limits.md
Labels: In Progress, Linguistic Suggestion
