Repository MicrosoftDocs/cpp-docs.ko-kr, pull requests merged in 2019-03, with the labels that each got.

#563 Update configuring-programs-for-64-bit-visual-cpp.md
  docs/build/configuring-programs-for-64-bit-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#564 Update configuring-programs-for-64-bit-visual-cpp.md
  docs/build/configuring-programs-for-64-bit-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#568 Update intrinsics-available-on-all-architectures.md
  docs/intrinsics/intrinsics-available-on-all-architectures.md
Labels: Accepted, Linguistic Suggestion

#570 Update walkthrough-compiling-a-native-cpp-program-on-the-command-line.md
  docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md
Labels: Accepted, Linguistic Suggestion

#571 Update walkthrough-compile-a-c-program-on-the-command-line.md
  docs/build/walkthrough-compile-a-c-program-on-the-command-line.md
Labels: Accepted, Linguistic Suggestion

#572 Update walkthrough-compiling-a-cpp-cli-program-on-the-command-line.md
  docs/build/walkthrough-compiling-a-cpp-cli-program-on-the-command-line.md
Labels: Accepted, Linguistic Suggestion

#574 Update setting-the-path-and-environment-variables-for-command-line-bu…
  docs/build/setting-the-path-and-environment-variables-for-command-line-builds.md
Labels: Accepted, Linguistic Suggestion

#576 Update msbuild-visual-cpp.md
  docs/build/msbuild-visual-cpp.md
Labels: Accepted, Linguistic Suggestion

#577 Update msbuild-visual-cpp-overview.md
  docs/build/msbuild-visual-cpp-overview.md
Labels: Accepted, Linguistic Suggestion

#578 Update build-system-changes.md
  docs/build/build-system-changes.md
Labels: Accepted, Linguistic Suggestion

#579 Update walkthrough-using-msbuild-to-create-a-visual-cpp-project.md
  docs/build/walkthrough-using-msbuild-to-create-a-visual-cpp-project.md
Labels: Accepted, Linguistic Suggestion

#580 Update how-to-use-build-events-in-msbuild-projects.md
  docs/build/how-to-use-build-events-in-msbuild-projects.md
Labels: Accepted, Linguistic Suggestion

#581 Update how-to-add-a-custom-build-step-to-msbuild-projects.md
  docs/build/how-to-add-a-custom-build-step-to-msbuild-projects.md
Labels: Accepted, Linguistic Suggestion

#582 Update how-to-add-custom-build-tools-to-msbuild-projects.md
  docs/build/how-to-add-custom-build-tools-to-msbuild-projects.md
Labels: Accepted, Linguistic Suggestion

#583 Update how-to-modify-the-target-framework-and-platform-toolset.md
  docs/build/how-to-modify-the-target-framework-and-platform-toolset.md
Labels: Accepted, Linguistic Suggestion

#548 Update containers-modern-cpp.md
  docs/cpp/containers-modern-cpp.md
Labels: Linguistic Suggestion, Partially Accepted

#550 Update overload-resolution-of-function-template-calls.md
  docs/cpp/overload-resolution-of-function-template-calls.md
Labels: Linguistic Suggestion, Partially Accepted

#551 Update partial-ordering-of-function-templates-cpp.md
  docs/cpp/partial-ordering-of-function-templates-cpp.md
Labels: Accepted, Linguistic Suggestion

#552 Update template-specialization-cpp.md
  docs/cpp/template-specialization-cpp.md
Labels: Accepted, Linguistic Suggestion

#555 Update templates-cpp.md
  docs/cpp/templates-cpp.md
Labels: Linguistic Suggestion, Partially Accepted

#556 Update template-specialization-cpp.md
  docs/cpp/template-specialization-cpp.md
Labels: Linguistic Suggestion, Partially Accepted

#557 Update convertbstrtostring.md
  docs/cpp/convertbstrtostring.md
Labels: Linguistic Suggestion, Partially Accepted

#559 Update set-com-error-handler.md
  docs/cpp/set-com-error-handler.md
Labels: Linguistic Suggestion, Partially Accepted

#575 Update nmake-reference.md
  docs/build/nmake-reference.md
Labels: Linguistic Suggestion, Partially Accepted

#589 Update compiler-options.md
  docs/build/reference/compiler-options.md
Labels: Accepted, Linguistic Suggestion

#565 Update compiling-a-c-cpp-program.md
  docs/build/reference/compiling-a-c-cpp-program.md
Labels: Linguistic Suggestion, Partially Accepted

#592 Update ai-specify-metadata-directories.md
  docs/build/reference/ai-specify-metadata-directories.md
Labels: Accepted, Linguistic Suggestion

#597 Update await-enable-coroutine-support.md
  docs/build/reference/await-enable-coroutine-support.md
Labels: Accepted, Linguistic Suggestion

#594 Update arch-x86.md
  docs/build/reference/arch-x86.md
Labels: Linguistic Suggestion, Partially Accepted

#602 Update TOC.md
  docs/build/reference/TOC.md
Labels: Technical Issue

#595 Update arch-x64.md
  docs/build/reference/arch-x64.md
Labels: Linguistic Suggestion, Partially Accepted

#600 Update c-preserve-comments-during-preprocessing.md
  docs/build/reference/c-preserve-comments-during-preprocessing.md
Labels: Linguistic Suggestion, Partially Accepted

#610 Update d-preprocessor-definitions.md
  docs/build/reference/d-preprocessor-definitions.md
Labels: Accepted, Linguistic Suggestion

#609 Update constexpr-control-constexpr-evaluation.md
  docs/build/reference/constexpr-control-constexpr-evaluation.md
Labels: Accepted

#606 Update c-preserve-comments-during-preprocessing.md
  docs/build/reference/c-preserve-comments-during-preprocessing.md
Labels: Accepted

#607 Update cgthreads-code-generation-threads.md
  docs/build/reference/cgthreads-code-generation-threads.md
Labels: Accepted

#608 Update clr-restrictions.md
  docs/build/reference/clr-restrictions.md
Labels: Accepted, Linguistic Suggestion

#618 Update e-preprocess-to-stdout.md
  docs/build/reference/e-preprocess-to-stdout.md
Labels: Accepted, Linguistic Suggestion

#611 Update name-resolution-for-dependent-types.md
  docs/cpp/name-resolution-for-dependent-types.md
Labels: In Progress, Linguistic Suggestion

#614 Update walkthrough-creating-and-using-a-static-library-cpp.md
  docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md
Labels: Accepted, Linguistic Suggestion

#615 Update walkthrough-creating-and-using-a-static-library-cpp.md
  docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md
Labels: Linguistic Suggestion, Partially Accepted

#616 Update walkthrough-creating-and-using-a-static-library-cpp.md
  docs/windows/walkthrough-creating-and-using-a-static-library-cpp.md
Labels: Linguistic Suggestion, Partially Accepted

#596 Update arch-arm.md
  docs/build/reference/arch-arm.md
Labels: Accepted, Linguistic Suggestion

#621 Update ep-preprocess-to-stdout-without-hash-line-directives.md
  docs/build/reference/ep-preprocess-to-stdout-without-hash-line-directives.md
Labels: Accepted, Linguistic Suggestion

#626 Update fa-fa-listing-file.md
  docs/build/reference/fa-fa-listing-file.md
Labels: Accepted, In Progress

#625 Update output-file-f-options.md
  docs/build/reference/output-file-f-options.md
Labels: Accepted, In Progress

#617 Update walkthrough-creating-and-using-a-dynamic-link-library-cpp.md
  docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md
Labels: Accepted, Linguistic Suggestion

#619 Update eh-exception-handling-model.md
  docs/build/reference/eh-exception-handling-model.md
Labels: Linguistic Suggestion, Partially Accepted

#623 Update execution-charset-set-execution-character-set.md
  docs/build/reference/execution-charset-set-execution-character-set.md
Labels: Linguistic Suggestion, Partially Accepted

#622 Update errorreport-report-internal-compiler-errors.md
  docs/build/reference/errorreport-report-internal-compiler-errors.md
Labels: Linguistic Suggestion, Partially Accepted

#624 Update f-set-stack-size.md
  docs/build/reference/f-set-stack-size.md
Labels: Linguistic Suggestion, Partially Accepted

#627 Update fd-ide-minimal-rebuild.md
  docs/build/reference/fd-ide-minimal-rebuild.md
Labels: Linguistic Suggestion, Partially Accepted
